/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupchatserver;

//import static groupchatserver.CheckLogin.ChecktoLogin;

import static groupchatserver.GroupChatServer.allPeople;
import static groupchatserver.GroupChatServer.clientsinetaddress;
import static groupchatserver.GroupChatServer.socket0;
import static groupchatserver.GroupChatServer.socket1;
import static groupchatserver.GroupChatServer.socket2;
import static groupchatserver.GroupChatServer.socket_notice;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;

/**
 *
 * @author user
 */
public class StartGroupCallServer extends javax.swing.JFrame{
    public static String add_server="192.168.0.21";
    public static int port=9000;
    public static int port_name = 9051;
    public static int clientsAnotherPlayerPort[]= {9003, 9004, 9005};
    public static int clientsNoticePort= 9006;
    
   
    public static ReceiveandSend_Thread0[] p = new ReceiveandSend_Thread0[10];
    byte[] buffer=new byte[1024];
    //public static HashMap <Integer, InetAddress> portMap = new HashMap<Integer, InetAddress>();
   
    public static AudioFormat getaudioformat(){
       float sampleRate=22050;
        int sampleSizeInBits=8;
        int channel=1;
        boolean signed=true;
        boolean bigEndian=false;
        return new AudioFormat(sampleRate, sampleSizeInBits, channel, signed, bigEndian);
    }
    public SourceDataLine audio_out;
    /**
     * Creates new form StartGroupCallServer
     */
    public StartGroupCallServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_start = new javax.swing.JButton();
        send_notice = new javax.swing.JTextField();
        btn_sendNotice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        send_notice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_noticeActionPerformed(evt);
            }
        });

        btn_sendNotice.setText("Send Notice");
        btn_sendNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendNoticeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(send_notice, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btn_sendNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_start)
                .addGap(39, 39, 39)
                .addComponent(send_notice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_sendNotice)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        
            // TODO add your handling code here:
            init_audio();
       
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_sendNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendNoticeActionPerformed
        // TODO add your handling code here:
        String notice=new String();
        notice=send_notice.getText();
        for(int i=0; i<allPeople; i++){
            try {
                DatagramPacket dp = new DatagramPacket(notice.getBytes(), 0, notice.length(), clientsinetaddress[i], clientsNoticePort );
                socket_notice.send(dp);
            } catch (IOException ex) {
                Logger.getLogger(StartGroupCallServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
      
    }//GEN-LAST:event_btn_sendNoticeActionPerformed

    private void send_noticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_noticeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_noticeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGroupCallServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGroupCallServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGroupCallServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGroupCallServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGroupCallServer().setVisible(true);
            }
        });
    }

    public void init_audio() {
        ReceiveandSend_Thread0 t0 = new ReceiveandSend_Thread0(socket0, 0);
        ReceiveandSend_Thread1 t1 = new ReceiveandSend_Thread1(socket1, 1);
        ReceiveandSend_Thread2 t2 = new ReceiveandSend_Thread2(socket2, 2);
        Name n = new Name();
        
        GroupChatServer.calling = true;
        t0.start();
        t1.start();
        t2.start();
        n.start();
        btn_start.setEnabled(false);
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendNotice;
    private javax.swing.JButton btn_start;
    private javax.swing.JTextField send_notice;
    // End of variables declaration//GEN-END:variables
}
